site_name: Sophon

docs_dir: mddocs

site_dir: docs

#theme: readthedocs
theme: yeti
#theme: united
#theme: alabaster

pages:
- Home: index.md
- API: api/sophon.md

# Copyright
copyright: 'Copyright (c) 2016 Zhenpeng Deng'


markdown_extensions:
- admonition