site_name: Sophon

docs_dir: mddocs

site_dir: docs

#theme: readthedocs
theme: yeti
#theme: united
#theme: alabaster

pages:
- Home: index.md
- User Guide: user_guide.md
- Configuration: configuration.md
- API: api/sophon/API.md


# Copyright
copyright: 'Copyright (c) 2016 <a href="http://www.monitor1379.com" target="blank">Zhenpeng Deng(monitor1379)</a>'


markdown_extensions:
- admonition